blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/xrequillart/magic-slash#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/xrequillart/magic-slash/discussions
    about: Ask questions and discuss ideas
